### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by jrselzer** [cryptoparty/flyers#20]
Hi, when trying to push new flyers, I get

remote: Permission to cryptoparty/flyers.git denied

What do I have to do to fix this?

**Comment by dawningsuncryptoparty** [comment]
Hi,

the way to push updates to any of the github.com/cryptoparty repositories is a bit different.

1. fork the repository: https://help.github.com/articles/fork-a-repo/
2. make any changes you want and push them to your fork
3. create a pull request: https://help.github.com/articles/creating-a-pull-request/
4. change will be reviewed before being accepted

The reasoning for this is that not everyone should be able to push anything and potentially troll the repository. While pull requests can be opened by anyone so we remain open for participation.

Does this help? If not please feel free to ask further questions.

**Comment by dawningsuncryptoparty** [comment]
resolved: see https://github.com/cryptoparty/flyers/pull/21
